### ISSUE TITLE
New version does not work with citizens in 1.8.x both spigot and craftbukit

### ISSUE THREAD

**Issue by gerice01** [DRE2N/DungeonsXL#315]
The new version has a bug with citizens and both plugin dont work.
I used craftbukkit and spigot but the problem was the same.
Where can i download older version by the way?

**Comment by gerice01** [comment]
[08:17:14 ERROR]: Error occurred while enabling DungeonsXL v0.15.6 (Is it up to date?)
java.lang.NoClassDefFoundError: net/citizensnpcs/api/npc/NPCRegistry
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_131]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_131]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_131]
        at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.8.0_131]
        at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.8.0_131]
        at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_131]
        at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_131]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_131]
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_131]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:195) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_131]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_131]
        at io.github.dre2n.dungeonsxl.mob.CitizensMobProvider.<init>(CitizensMobProvider.java:36) ~[?:?]
        at io.github.dre2n.dungeonsxl.mob.ExternalMobProviders.<init>(ExternalMobProviders.java:40) ~[?:?]
        at io.github.dre2n.dungeonsxl.DungeonsXL.loadExternalMobProviders(DungeonsXL.java:480) ~[?:?]
        at io.github.dre2n.dungeonsxl.DungeonsXL.loadCore(DungeonsXL.java:274) ~[?:?]
        at io.github.dre2n.dungeonsxl.DungeonsXL.onEnable(DungeonsXL.java:140) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.ClassNotFoundException: net.citizensnpcs.api.npc.NPCRegistry
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_131]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_131]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_131]
        ... 31 more

**Comment by gerice01** [comment]
!Update same problem in 1.9.x tested all version!
java.lang.NoClassDefFoundError: net/citizensnpcs/api/npc/NPCRegistry
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_131]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_131]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_131]
        at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.8.0_131]
        at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.8.0_131]
        at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_131]
        at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_131]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_131]
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_131]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-4af49dc-c5e9a16]
        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:195) ~[spigot.jar:git-Spigot-4af49dc-c5e9a16]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97) ~[spigot.jar:git-Spigot-4af49dc-c5e9a16]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-4af49dc-c5e9a16]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_131]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_131]
        at io.github.dre2n.dungeonsxl.mob.CitizensMobProvider.<init>(CitizensMobProvider.java:36) ~[?:?]
        at io.github.dre2n.dungeonsxl.mob.ExternalMobProviders.<init>(ExternalMobProviders.java:40) ~[?:?]
        at io.github.dre2n.dungeonsxl.DungeonsXL.loadExternalMobProviders(DungeonsXL.java:480) ~[?:?]
        at io.github.dre2n.dungeonsxl.DungeonsXL.loadCore(DungeonsXL.java:274) ~[?:?]
        at io.github.dre2n.dungeonsxl.DungeonsXL.onEnable(DungeonsXL.java:140) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[spigot.jar:git-Spigot-4af49dc-c5e9a16]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-4af49dc-c5e9a16]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-4af49dc-c5e9a16]
        at org.bukkit.craftbukkit.v1_9_R2.CraftServer.loadPlugin(CraftServer.java:361) [spigot.jar:git-Spigot-4af49dc-c5e9a16]
        at org.bukkit.craftbukkit.v1_9_R2.CraftServer.enablePlugins(CraftServer.java:321) [spigot.jar:git-Spigot-4af49dc-c5e9a16]
        at net.minecraft.server.v1_9_R2.MinecraftServer.t(MinecraftServer.java:416) [spigot.jar:git-Spigot-4af49dc-c5e9a16]
        at net.minecraft.server.v1_9_R2.MinecraftServer.l(MinecraftServer.java:381) [spigot.jar:git-Spigot-4af49dc-c5e9a16]
        at net.minecraft.server.v1_9_R2.MinecraftServer.a(MinecraftServer.java:336) [spigot.jar:git-Spigot-4af49dc-c5e9a16]
        at net.minecraft.server.v1_9_R2.DedicatedServer.init(DedicatedServer.java:268) [spigot.jar:git-Spigot-4af49dc-c5e9a16]
        at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:532) [spigot.jar:git-Spigot-4af49dc-c5e9a16]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.ClassNotFoundException: net.citizensnpcs.api.npc.NPCRegistry
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_131]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-4af49dc-c5e9a16]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-4af49dc-c5e9a16]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_131]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_131]

**Comment by gerice01** [comment]
And i have a big question.If i don't want classes and i want that the players use their's iventory? How do i set that?

**Comment by Sataniel98** [comment]
Your error occurs because Citizens is not loaded correctly. DungeonsXL shouldn't have any influence on whether Citizens loads correctly or not. You find information for your question in the FAQ in the wiki, it's a very common one.

https://github.com/DRE2N/DungeonsXL/wiki/faq#how-can-i-make-it-so-that-players-play-dungeons-with-their-own-items

**Comment by gerice01** [comment]
I can read too, so i understood that citizens cannot be loaded but how can i make it work? Thats the question.

**Comment by Tiplish** [comment]
Have you check if citizen is loaded correctly on your server and if it works without Dungeonxl?

**Comment by Sataniel98** [comment]
I'm not an expert for Citizens, but if I'd had to guess I'd say your data is corrupted or, which is more likely, you are using an incompatible version. Citizens uses internal methods of the Minecraft server that are always subject to change, so its builds usually work with just one or very few Minecraft versions. Also note that sometimes, the latest Minecraft version is not yet selectable for developers at BukkitDev when they upload a plugin jar, so sometimes builds are registered for the wrong version and you need to look at the changelog to make sure the build you're downloading really is intended to be used with your version. Because of your stacktraces, I assume you're running Spigot (or a Spigot fork like PaperSpigot) for 1.8.8. That would be [this one](https://dev.bukkit.org/projects/citizens/files/901556) even though it is registered for 1.8.1 (which never even had a Spigot build!)
