### ISSUE TITLE
Internal error on any command, not functioning

### ISSUE THREAD

**Issue by H-Duck** [DRE2N/DungeonsXL#1091]
**Description**

Running any command causes the output of "An internal error occurred while attempting to perform this command", and the command does not do its intended purpose

**Reproduce**

1. Run any command from this plugin

**Expected behavior**

The command functions properly, or an error message is displayed if the incorrect syntax is used

**Extra info**
Current plugins folder:
![image](https://user-images.githubusercontent.com/75576430/160029083-15eea93e-c16a-4d85-895e-c2439fa23b52.png)

**Relevant configuration files**

```
[23:58:00] [Server thread/INFO]: ducksworth_ issued server command: /dxl
[23:58:00] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'dxl' in plugin DungeonsXL v0.18-PRE-02
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:905) ~[paper-1.18.2.jar:git-Paper-267]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2306) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2117) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2098) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-267]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1399) ~[paper-1.18.2.jar:git-Paper-267]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[paper-1.18.2.jar:git-Paper-267]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1376) ~[paper-1.18.2.jar:git-Paper-267]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1369) ~[paper-1.18.2.jar:git-Paper-267]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1347) ~[paper-1.18.2.jar:git-Paper-267]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1229) ~[paper-1.18.2.jar:git-Paper-267]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-267]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoSuchMethodError: 'net.kyori.adventure.text.minimessage.MiniMessage net.kyori.adventure.text.minimessage.MiniMessage.get()'
	at de.erethon.dungeonsxl.util.commons.chat.MessageUtil.parse(MessageUtil.java:339) ~[dungeonsxl-dist-0.18-PRE-02.jar:?]
	at de.erethon.dungeonsxl.util.commons.chat.MessageUtil.sendCenteredMessage(MessageUtil.java:222) ~[dungeonsxl-dist-0.18-PRE-02.jar:?]
	at de.erethon.dungeonsxl.command.MainCommand.onExecute(MainCommand.java:62) ~[dungeonsxl-dist-0.18-PRE-02.jar:?]
	at de.erethon.dungeonsxl.util.commons.command.DRECommand.execute(DRECommand.java:163) ~[dungeonsxl-dist-0.18-PRE-02.jar:?]
	at de.erethon.dungeonsxl.util.commons.command.DRECommandExecutor.onCommand(DRECommandExecutor.java:83) ~[dungeonsxl-dist-0.18-PRE-02.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	... 21 more

```

**Comment by Sataniel98** [comment]
That build didn't work with Paper 1.18.2. A fix has been uploaded to Spigot.
