### ISSUE TITLE
Issue with using the help command (Paper 1.18.2)

### ISSUE THREAD

**Issue by snowy6409** [DRE2N/DungeonsXL#1096]
**Description**

When I do a fresh install of the dev build on paper 1.18.2 and try to run /dxl help it throws an error about a missing method for kyori. 
I don't know if this is a known issue, or I am doing something wrong and grabbed the wrong files, or if it is because the build failed for the latest GitHub push from you and it is using the old jar.

**Log File**

```
[22:35:11] [Server thread/INFO]: snowy6409 issued server command: /dxl help
[22:35:11] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'dxl' in plugin DungeonsXL v0.18-PRE-02
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906) ~[paper-1.18.2.jar:git-Paper-299]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2306) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2117) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2098) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-299]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1399) ~[paper-1.18.2.jar:git-Paper-299]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[paper-1.18.2.jar:git-Paper-299]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1376) ~[paper-1.18.2.jar:git-Paper-299]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1369) ~[paper-1.18.2.jar:git-Paper-299]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1503) ~[paper-1.18.2.jar:git-Paper-299]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1225) ~[paper-1.18.2.jar:git-Paper-299]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-299]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoSuchMethodError: 'net.kyori.adventure.text.minimessage.MiniMessage net.kyori.adventure.text.minimessage.MiniMessage.get()'
	at de.erethon.dungeonsxl.util.commons.chat.MessageUtil.parse(MessageUtil.java:339) ~[dungeonsxl-dist-0.18-PRE-02 (1).jar:?]
	at de.erethon.dungeonsxl.util.commons.chat.MessageUtil.sendCenteredMessage(MessageUtil.java:222) ~[dungeonsxl-dist-0.18-PRE-02 (1).jar:?]
	at de.erethon.dungeonsxl.util.commons.chat.MessageUtil.sendPluginTag(MessageUtil.java:242) ~[dungeonsxl-dist-0.18-PRE-02 (1).jar:?]
	at de.erethon.dungeonsxl.command.HelpCommand.onExecute(HelpCommand.java:66) ~[dungeonsxl-dist-0.18-PRE-02 (1).jar:?]
	at de.erethon.dungeonsxl.util.commons.command.DRECommand.execute(DRECommand.java:163) ~[dungeonsxl-dist-0.18-PRE-02 (1).jar:?]
	at de.erethon.dungeonsxl.util.commons.command.DRECommandExecutor.onCommand(DRECommandExecutor.java:67) ~[dungeonsxl-dist-0.18-PRE-02 (1).jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	... 21 more
[22:41:55] [Server thread/INFO]: Plugins (2): DungeonsXL, ItemsXL
```

**Comment by Sataniel98** [comment]
This build doesn't work on Paper 1.18.2. The latest one fixes it.

**Comment by snowy6409** [comment]
> This build doesn't work on Paper 1.18.2. The latest one fixes it.

Where would one go to find the latest one.
Spigot?
or
http://erethon.de/repo/de/erethon/dungeonsxl/dungeonsxl-dist/
or somewhere else?

**Comment by Sataniel98** [comment]
Spigot or build from source

**Comment by snowy6409** [comment]
Just re-downloaded the plguin from spigot and also itemxl from spigot. Now I have a different error I am getting a.
```
[14:07:10] [Server thread/INFO]: [DungeonsXL] Could not find compatible Citizens plugin. The mob provider Citizens ("CI") will not get enabled...
[14:07:10] [Server thread/ERROR]: Error occurred while enabling DungeonsXL v0.18-SNAPSHOT-1149 (Is it up to date?)
java.lang.NullPointerException: Cannot read the array length because "<local3>" is null
	at de.erethon.bedrock.misc.FileUtil.copyDir(FileUtil.java:70) ~[itemsxl-1.1.jar:?]
	at de.erethon.dungeonsxl.DungeonsXL.checkState(DungeonsXL.java:449) ~[dungeonsxl-dist-0.18-SNAPSHOT-1149.jar:?]
	at de.erethon.dungeonsxl.DungeonsXL.onEnable(DungeonsXL.java:250) ~[dungeonsxl-dist-0.18-SNAPSHOT-1149.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[paper-1.18.2.jar:git-Paper-299]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.18.2.jar:git-Paper-299]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:664) ~[paper-1.18.2.jar:git-Paper-299]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.18.2.jar:git-Paper-299]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-299]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.18.2.jar:git-Paper-299]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-299]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[14:07:10] [Server thread/INFO]: [DungeonsXL] Disabling DungeonsXL v0.18-SNAPSHOT-1149
```
